query Project($id:ID!){
  project(id:$id){
    id
    title
    gallery{
      id
      url
    }   
  }
}


# query Project($id:ID!){
#   project(id:$id){
#     id
#     title
#     gallery{
#       id
#       url
#     }   
#   }
# }